<?php

function dnapair_menu() {
    $items['dnapair'] = array(
        'title' => 'DNA pairing',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dnapair_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dnapair_success'] = array(
        'title' => 'Your DNA pair!',
        'page callback' => 'dnapair_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dnapair_form() {
    $form['half_h'] = array(
        '#title' => 'Enter half of the helix to get the other',
        '#type' => 'textfield',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_h'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}

function element_validate_h($element) {
    $valid_h = array('A', 'T', 'C', 'G', ' ');

    $h_array = strtoupper($element['#value']);
    $h_array = str_split($h_array);

    foreach($h_array as $letter) {
        if (!in_array($letter, $valid_h)) {
            form_error($element, t('Only A T C or G are allowed'));
        }
    }
}

function make_h($input) {
    $valid_h = array('A', 'T', 'C', 'G');

    $input_h_array = str_split($input);
    $output = array();

    foreach ($input_h_array as $letter) {
        $letter = strtoupper($letter);
        if (in_array($letter, $valid_h)) {
            if ($letter == 'A') {
                array_push($output, 'T');
            } elseif ($letter == 'T') {
                array_push($output, 'A');
            } elseif ($letter == 'C') {
                array_push($output, 'G');
            } elseif ($letter == 'G') {
                array_push($output, 'C');
            }
        }
            else {
                array_push($output, '&nbsp');
            }
    }
    return implode('', $output);
}


function dnapair_form_submit($form, &$form_state) {
    $input = $form_state['values']['half_h'];
    $_SESSION['original'] = $input;
    $result = make_h($input);
    $_SESSION['dnapair'] = $result;

    $form_state['redirect'] = 'dnapair_success';
}

function dnapair_success() {
    $input = $_SESSION['original'];
    $dnapair = $_SESSION['dnapair'];
    return '<br><p><strong>Original helix</strong>: ' . $input . '<hr><strong>Other half of the helix is:</strong>: ' . $dnapair . '</p>';
}
